#!/bin/bash
echo __SAT_ENV__EXPORT__INCLUDED

echo "UPDATE ENV: CUSTOM_ENV2=THIS IS CUSTOM ENV FROM BASH2"

echo __SAT_ENV__EXPORT:__SAT_ENV__CUSTOM_ENV2="THIS IS CUSTOM ENV2 FROM BASH"

echo "UPDATE ENV: $1=$2"
echo __SAT_ENV__EXPORT:__SAT_ENV__$1=$2
