# Generated by Django 4.2.14 on 2025-12-29 07:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='配置名称，用于标识不同的AI模型配置', max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google (Gemini)'), ('anthropic', 'Anthropic (Claude)'), ('azure_openai', 'Azure OpenAI'), ('ollama', 'Ollama (Local)'), ('custom', 'Custom API')], help_text='AI模型提供商', max_length=20)),
                ('model_name', models.CharField(help_text='具体的模型名称，如 gpt-4, claude-3-sonnet 等', max_length=100)),
                ('api_url', models.URLField(help_text='API端点URL')),
                ('api_key_encrypted', models.TextField(help_text='加密存储的API密钥')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='额外的配置参数，如温度、最大token等')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用此配置')),
                ('is_default', models.BooleanField(default=False, help_text='是否为默认配置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0, help_text='使用次数统计')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='最后使用时间', null=True)),
            ],
            options={
                'verbose_name': 'AI模型配置',
                'verbose_name_plural': 'AI模型配置',
                'db_table': 'ai_model_config',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google (Gemini)'), ('anthropic', 'Anthropic (Claude)'), ('azure_openai', 'Azure OpenAI'), ('ollama', 'Ollama (Local)'), ('custom', 'Custom API')], max_length=20, unique=True)),
                ('default_api_url', models.URLField(help_text='默认API端点URL')),
                ('supported_models', models.JSONField(default=list, help_text='支持的模型列表')),
                ('default_config', models.JSONField(default=dict, help_text='默认配置参数')),
                ('required_fields', models.JSONField(default=list, help_text='必需的配置字段')),
                ('documentation_url', models.URLField(blank=True, help_text='文档链接')),
            ],
            options={
                'verbose_name': 'AI模型模板',
                'verbose_name_plural': 'AI模型模板',
                'db_table': 'ai_model_template',
            },
        ),
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('category', models.CharField(choices=[('protocol', 'Protocol Configuration'), ('generator', 'Test Generator Configuration'), ('monitoring', 'Monitoring Configuration'), ('complete', 'Complete Campaign Configuration')], help_text='Template category', max_length=20)),
                ('protocol_config', models.JSONField(blank=True, help_text='Protocol configuration', null=True)),
                ('generator_config', models.JSONField(blank=True, help_text='Generator configuration', null=True)),
                ('monitoring_config', models.JSONField(blank=True, help_text='Monitoring configuration', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is a default template')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times used')),
            ],
            options={
                'verbose_name': 'IoT Config Template',
                'verbose_name_plural': 'IoT Config Templates',
                'db_table': 'iot_config_templates',
                'ordering': ['-is_default', '-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FrameField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Field name (user-editable)', max_length=100)),
                ('field_id', models.CharField(help_text='Field identifier', max_length=100)),
                ('field_type', models.CharField(choices=[('hex', 'Hexadecimal'), ('dec', 'Decimal'), ('auto', 'Auto-generated'), ('binary', 'Binary'), ('string', 'String')], default='hex', help_text='Field data type', max_length=20)),
                ('value', models.TextField(help_text='Field value')),
                ('default_value', models.TextField(blank=True, help_text='Default field value')),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text', max_length=255)),
                ('is_required', models.BooleanField(default=False, help_text='Whether field is required')),
                ('field_order', models.IntegerField(default=0, help_text='Field order within frame')),
                ('bit_offset', models.IntegerField(blank=True, help_text='Bit offset within frame', null=True)),
                ('bit_length', models.IntegerField(blank=True, help_text='Field length in bits', null=True)),
                ('target_bits', models.CharField(blank=True, help_text="Bit positions to fuzz (e.g., '0,1,7' or '0-7')", max_length=255)),
            ],
            options={
                'verbose_name': 'Frame Field',
                'verbose_name_plural': 'Frame Fields',
                'db_table': 'iot_frame_fields',
                'ordering': ['test_case', 'field_order'],
            },
        ),
        migrations.CreateModel(
            name='FuzzingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campaign name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Campaign description')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', help_text='Campaign status', max_length=20)),
                ('protocol_type', models.CharField(help_text='Primary protocol type for this campaign', max_length=50)),
                ('protocol_config', models.JSONField(default=dict, help_text='Protocol-specific configuration')),
                ('generator_config', models.JSONField(default=dict, help_text='Test generation configuration')),
                ('monitoring_config', models.JSONField(default=dict, help_text='Monitoring and logging configuration')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('total_iterations', models.IntegerField(default=0)),
                ('total_cases', models.IntegerField(default=0)),
                ('passed_cases', models.IntegerField(default=0)),
                ('failed_cases', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_uuid', models.CharField(blank=True, db_index=True, help_text='Runtime UUID for this campaign', max_length=64, null=True, unique=True)),
                ('fuzzer_instance_id', models.CharField(blank=True, help_text='Reference to fuzzer instance', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'IoT Fuzzing Campaign',
                'verbose_name_plural': 'IoT Fuzzing Campaigns',
                'db_table': 'iot_fuzzing_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IoTConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Configuration description')),
                ('protocol_type', models.CharField(choices=[('can', 'CAN Bus'), ('uart', 'UART/Serial'), ('spi', 'SPI'), ('i2c', 'I2C'), ('ethernet', 'Ethernet'), ('doip', 'DoIP')], help_text='Protocol type', max_length=20)),
                ('protocol_settings', models.JSONField(default=dict, help_text='Protocol-specific settings')),
                ('generator_type', models.CharField(default='radamsa', help_text='Fuzzing generator type', max_length=50)),
                ('generator_settings', models.JSONField(default=dict, help_text='Generator-specific settings')),
                ('campaign_settings', models.JSONField(default=dict, help_text='Test campaign settings')),
                ('monitoring_settings', models.JSONField(default=dict, help_text='Monitoring and logging settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
            ],
            options={
                'verbose_name': 'IoT Configuration',
                'verbose_name_plural': 'IoT Configurations',
                'db_table': 'iot_configurations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('enabled', models.BooleanField(default=True)),
                ('module_path', models.CharField(help_text='Python module path to the plugin class', max_length=255)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('parameters', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PluginGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_type', models.CharField(choices=[('can', 'CAN Bus'), ('uart', 'UART/Serial'), ('spi', 'SPI'), ('i2c', 'I2C'), ('ethernet', 'Ethernet'), ('doip', 'DoIP')], help_text='Protocol type', max_length=20)),
                ('settings', models.JSONField(default=dict, help_text='Protocol-specific configuration settings')),
            ],
            options={
                'verbose_name': 'Protocol Configuration',
                'verbose_name_plural': 'Protocol Configurations',
                'db_table': 'iot_protocol_configurations',
            },
        ),
        migrations.CreateModel(
            name='TestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Test group name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Test group description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', help_text='Test group priority', max_length=20)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this group is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocol_type', models.CharField(help_text='Protocol type for this group', max_length=50)),
                ('total_cases', models.IntegerField(default=0, help_text='Total test cases in group')),
                ('completed_cases', models.IntegerField(default=0, help_text='Completed test cases')),
                ('failed_cases', models.IntegerField(default=0, help_text='Failed test cases')),
                ('campaign', models.ForeignKey(blank=True, help_text='Associated campaign (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_groups', to='iotsploit_django.fuzzingcampaign')),
            ],
            options={
                'verbose_name': 'IoT Test Group',
                'verbose_name_plural': 'IoT Test Groups',
                'db_table': 'iot_test_groups',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Test case name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Test case description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', help_text='Test case priority', max_length=20)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this test case is enabled')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Test case creation time')),
                ('frame_name', models.CharField(default='Protocol Frame', help_text='Name of the protocol frame', max_length=255)),
                ('frame_description', models.TextField(blank=True, help_text='Description of the protocol frame')),
                ('timeout_seconds', models.FloatField(default=5.0, help_text='Test timeout in seconds')),
                ('iterations', models.IntegerField(default=100, help_text='Number of test iterations')),
                ('expected_response', models.JSONField(blank=True, help_text='Expected response pattern', null=True)),
                ('execution_count', models.IntegerField(default=0, help_text='Number of times executed')),
                ('last_executed', models.DateTimeField(blank=True, help_text='Last execution time', null=True)),
                ('last_result', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('error', 'Error'), ('crash', 'Crash')], help_text='Last execution result', max_length=20, null=True)),
                ('group', models.ForeignKey(help_text='Associated test group', on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='iotsploit_django.testgroup')),
                ('protocol_config', models.ForeignKey(help_text='Protocol configuration for this test case', on_delete=django.db.models.deletion.CASCADE, to='iotsploit_django.protocolconfiguration')),
            ],
            options={
                'verbose_name': 'IoT Test Case',
                'verbose_name_plural': 'IoT Test Cases',
                'db_table': 'iot_test_cases',
                'ordering': ['group', 'priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PluginSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.SmallIntegerField(default=100)),
                ('ignore_fail', models.BooleanField(default=False, help_text='Continue execution even if the plugin fails')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotsploit_django.plugin')),
                ('plugingroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotsploit_django.plugingroup')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='PluginGroupTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.SmallIntegerField(default=100)),
                ('ignore_fail', models.BooleanField(default=False, help_text='Continue execution even if the child group fails')),
                ('force_exec', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='iotsploit_django.plugingroup')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='iotsploit_django.plugingroup')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='plugingroup',
            name='plugin_groups',
            field=models.ManyToManyField(through='iotsploit_django.PluginGroupTree', to='iotsploit_django.plugingroup'),
        ),
        migrations.AddField(
            model_name='plugingroup',
            name='plugins',
            field=models.ManyToManyField(through='iotsploit_django.PluginSequence', to='iotsploit_django.plugin'),
        ),
        migrations.CreateModel(
            name='LiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], help_text='Log level', max_length=20)),
                ('category', models.CharField(choices=[('system', 'System'), ('fuzzer', 'Fuzzer'), ('protocol', 'Protocol'), ('test', 'Test Execution'), ('result', 'Result Processing')], help_text='Log category', max_length=20)),
                ('source', models.CharField(help_text='Log source component', max_length=100)),
                ('message', models.TextField(help_text='Log message')),
                ('extra_data', models.JSONField(blank=True, help_text='Additional structured data', null=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='Associated campaign', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='iotsploit_django.fuzzingcampaign')),
            ],
            options={
                'verbose_name': 'IoT Live Log',
                'verbose_name_plural': 'IoT Live Logs',
                'db_table': 'iot_live_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FuzzingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(help_text='Rule name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Rule description')),
                ('enabled', models.BooleanField(default=True, help_text='Whether rule is enabled')),
                ('target_type', models.CharField(choices=[('field', 'Field-level'), ('bit', 'Bit-level'), ('byte', 'Byte-level'), ('frame', 'Frame-level')], help_text='Type of fuzzing target', max_length=20)),
                ('target_bits', models.CharField(blank=True, help_text="Bit positions to fuzz (e.g., '0,1,7' or '0-7')", max_length=255)),
                ('strategy', models.CharField(choices=[('random', 'Random'), ('sequential', 'Sequential'), ('pattern_based', 'Pattern-based'), ('boundary', 'Boundary Testing'), ('bit_flip', 'Bit Flipping'), ('injection', 'Injection')], default='random', help_text='Fuzzing strategy to use', max_length=20)),
                ('strategy_config', models.JSONField(default=dict, help_text='Strategy-specific configuration parameters')),
                ('iterations_per_rule', models.IntegerField(default=100, help_text='Number of iterations for this rule')),
                ('priority', models.IntegerField(default=50, help_text='Rule execution priority (0-100)')),
                ('target_field', models.ForeignKey(blank=True, help_text='Target field (for field-level fuzzing)', null=True, on_delete=django.db.models.deletion.CASCADE, to='iotsploit_django.framefield')),
                ('test_case', models.ForeignKey(help_text='Associated test case', on_delete=django.db.models.deletion.CASCADE, related_name='fuzzing_rules', to='iotsploit_django.testcase')),
            ],
            options={
                'verbose_name': 'Fuzzing Rule',
                'verbose_name_plural': 'Fuzzing Rules',
                'db_table': 'iot_fuzzing_rules',
                'ordering': ['test_case', '-priority', 'rule_name'],
            },
        ),
        migrations.CreateModel(
            name='FuzzingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_number', models.IntegerField(help_text='Iteration number')),
                ('executed_at', models.DateTimeField(auto_now_add=True, help_text='Execution timestamp')),
                ('payload_hex', models.TextField(help_text='Test payload in hex format')),
                ('payload_size', models.IntegerField(help_text='Payload size in bytes')),
                ('status', models.CharField(choices=[('success', 'Success'), ('crash', 'Crash'), ('timeout', 'Timeout'), ('error', 'Error'), ('anomaly', 'Anomaly')], help_text='Execution result status', max_length=20)),
                ('response_hex', models.TextField(blank=True, help_text='Response data in hex format')),
                ('response_time_ms', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('crashed', models.BooleanField(default=False, help_text='Whether execution crashed')),
                ('crash_info', models.TextField(blank=True, help_text='Crash details and stack trace')),
                ('artifact_path', models.CharField(blank=True, help_text='Path to stored artifacts', max_length=500)),
                ('campaign', models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='iotsploit_django.fuzzingcampaign')),
                ('test_case', models.ForeignKey(blank=True, help_text='Associated test case', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='iotsploit_django.testcase')),
            ],
            options={
                'verbose_name': 'IoT Fuzzing Result',
                'verbose_name_plural': 'IoT Fuzzing Results',
                'db_table': 'iot_fuzzing_results',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddField(
            model_name='framefield',
            name='test_case',
            field=models.ForeignKey(help_text='Associated test case', on_delete=django.db.models.deletion.CASCADE, related_name='frame_fields', to='iotsploit_django.testcase'),
        ),
        migrations.AddIndex(
            model_name='testgroup',
            index=models.Index(fields=['enabled', 'priority'], name='iot_test_gr_enabled_77ec6c_idx'),
        ),
        migrations.AddIndex(
            model_name='testgroup',
            index=models.Index(fields=['protocol_type'], name='iot_test_gr_protoco_68e63e_idx'),
        ),
        migrations.AddIndex(
            model_name='testgroup',
            index=models.Index(fields=['campaign'], name='iot_test_gr_campaig_211f82_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['group', 'enabled'], name='iot_test_ca_group_i_f9ed8b_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['priority'], name='iot_test_ca_priorit_4b099c_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['enabled'], name='iot_test_ca_enabled_f8a691_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['last_result'], name='iot_test_ca_last_re_49d8e6_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['protocol_config'], name='iot_test_ca_protoco_8fae64_idx'),
        ),
        migrations.AddIndex(
            model_name='livelog',
            index=models.Index(fields=['campaign', 'timestamp'], name='iot_live_lo_campaig_f532aa_idx'),
        ),
        migrations.AddIndex(
            model_name='livelog',
            index=models.Index(fields=['level'], name='iot_live_lo_level_eca05e_idx'),
        ),
        migrations.AddIndex(
            model_name='livelog',
            index=models.Index(fields=['category'], name='iot_live_lo_categor_da4d75_idx'),
        ),
        migrations.AddIndex(
            model_name='fuzzingrule',
            index=models.Index(fields=['test_case', 'enabled'], name='iot_fuzzing_test_ca_580832_idx'),
        ),
        migrations.AddIndex(
            model_name='fuzzingrule',
            index=models.Index(fields=['target_type'], name='iot_fuzzing_target__d41f13_idx'),
        ),
        migrations.AddIndex(
            model_name='fuzzingrule',
            index=models.Index(fields=['strategy'], name='iot_fuzzing_strateg_bb9cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='fuzzingrule',
            index=models.Index(fields=['priority'], name='iot_fuzzing_priorit_c43920_idx'),
        ),
        migrations.AddIndex(
            model_name='fuzzingrule',
            index=models.Index(fields=['target_bits'], name='iot_fuzzing_target__ccb30e_idx'),
        ),
        migrations.AddIndex(
            model_name='fuzzingresult',
            index=models.Index(fields=['campaign', 'test_case'], name='iot_fuzzing_campaig_814626_idx'),
        ),
        migrations.AddIndex(
            model_name='fuzzingresult',
            index=models.Index(fields=['status'], name='iot_fuzzing_status_c3247f_idx'),
        ),
        migrations.AddIndex(
            model_name='fuzzingresult',
            index=models.Index(fields=['executed_at'], name='iot_fuzzing_execute_7a76be_idx'),
        ),
        migrations.AddIndex(
            model_name='framefield',
            index=models.Index(fields=['test_case', 'field_order'], name='iot_frame_f_test_ca_f00d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='framefield',
            index=models.Index(fields=['field_type'], name='iot_frame_f_field_t_703c16_idx'),
        ),
        migrations.AddIndex(
            model_name='framefield',
            index=models.Index(fields=['target_bits'], name='iot_frame_f_target__191a56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='framefield',
            unique_together={('test_case', 'field_id')},
        ),
    ]
