# Generated by Django 4.2.14 on 2026-09-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iotsploit_django", "0004_plugin_requirements"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginPaths",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exploit_dir",
                    models.CharField(blank=True, default="", max_length=4096),
                ),
                (
                    "device_dir",
                    models.CharField(blank=True, default="", max_length=4096),
                ),
            ],
        ),
    ]
