# Generated by Django 4.2.14 on 2026-09-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iotsploit_django", "0005_pluginpaths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iotconfiguration",
            name="protocol_type",
            field=models.CharField(
                choices=[
                    ("usbtmc", "USBTMC"),
                    ("can", "CAN Bus"),
                    ("uart", "UART/Serial"),
                    ("spi", "SPI"),
                    ("i2c", "I2C"),
                    ("ethernet", "Ethernet"),
                    ("doip", "DoIP"),
                ],
                help_text="Protocol type",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="protocolconfiguration",
            name="protocol_type",
            field=models.CharField(
                choices=[
                    ("usbtmc", "USBTMC"),
                    ("can", "CAN Bus"),
                    ("uart", "UART/Serial"),
                    ("spi", "SPI"),
                    ("i2c", "I2C"),
                    ("ethernet", "Ethernet"),
                    ("doip", "DoIP"),
                ],
                help_text="Protocol type",
                max_length=20,
            ),
        ),
    ]
