"""Compatibility exports for legacy HTTP views."""

from iotsploit_django.view_handlers.plugin_views import (
    list_plugins,
    list_enabled_exploit_plugins,
    discovered_exploit_plugins,
    enable_exploit_plugin,
    disable_exploit_plugin,
    list_enabled_plugin_groups,
    get_plugin_group,
    list_device_drivers,
    execute_plugin,
    list_plugin_info,
    list_groups,
    execute_group,
    execute_plugin_async,
    stop_plugin_async,
    list_device_commands,
    execute_device_command,
    create_group,
    delete_group,
    cleanup_plugins,
    get_plugin_code,
    save_plugin_code,
    get_driver_states,
    enable_driver,
    disable_driver,
)
from iotsploit_django.view_handlers.misc_legacy_views import (
    active_channels,
    list_urls,
    set_log_level,
)
from iotsploit_django.view_handlers.firmware_legacy_views import (
    file_download,
)
from iotsploit_django.view_handlers.tool_views import (
    get_tools_status,
    refresh_tools,
    get_tool_details,
    get_system_health,
)
from iotsploit_django.view_handlers.recovery_views import (
    list_recovery_drivers,
    execute_recovery,
)

__all__ = [
    "list_plugins",
    "list_enabled_exploit_plugins",
    "discovered_exploit_plugins",
    "enable_exploit_plugin",
    "disable_exploit_plugin",
    "list_enabled_plugin_groups",
    "get_plugin_group",
    "list_device_drivers",
    "execute_plugin",
    "list_plugin_info",
    "list_groups",
    "execute_group",
    "execute_plugin_async",
    "stop_plugin_async",
    "list_device_commands",
    "execute_device_command",
    "create_group",
    "delete_group",
    "cleanup_plugins",
    "get_plugin_code",
    "save_plugin_code",
    "get_driver_states",
    "enable_driver",
    "disable_driver",
    "active_channels",
    "list_urls",
    "set_log_level",
    "file_download",
    "get_tools_status",
    "refresh_tools",
    "get_tool_details",
    "get_system_health",
    "list_recovery_drivers",
    "execute_recovery",
]
