[tool.poetry]
name = "socketcan-driver"
version = "0.0.6"
description = "SocketCAN Device Driver Plugin for IoTSploit"
authors = ["IoTSploit Team <support@iotsploit.org>"]
license = "GPL-3.0-or-later"
keywords = ["iot", "security", "can", "socketcan", "driver", "plugin"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Topic :: Security",
    "Topic :: System :: Hardware",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
packages = [
    { include = "drv_socketcan.py" },
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
iotsploit-core = "^0.0.6"
python-can = "4.5.0"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
